---
server:
  port: 8089
spring:
  application:
    name: "authentis-users"
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authentis-users-db}"
    username: "${DB_USER:domeni.ngameni}"
    password: "${DB_PASSWORD:authentis-users-password}"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${ISSUER-URI:http://localhost:8080/realms/authentis-user}"
          jwk-set-uri: "${jwtk-set-uri:http://localhost:8080/realms/authentis-user/protocol/openid-connect/certs}"
logging:
  level:
    org.springframework.security: "DEBUG"
    org.springframework.web: "DEBUG"
keycloak:
  admin-client:
    server-url: "${KEYCLOAK_SERVER_URL:http://localhost:8080}"
    realm: "${KEYCLOAK_REALM:authentis-user}"
    client-id: "${KEYCLOAK_ADMIN_CLIENT_ID:authentis-users}"
    client-secret: "${KEYCLOAK_ADMIN_CLIENT_SECRET:9NUbJeoBdCvqdZIgrC3etSWdcCFn12GX}"
